#!/bin/bash
#SBATCH --partition=deeplearn
#SBATCH --gres=gpu:A100:1
#SBATCH --time=12:00:00
#SBATCH --ntasks=1
#SBATCH --job-name=mingbin.calculate_entropy
#SBATCH --cpus-per-task=16
#SBATCH -A punim0478
#SBATCH --qos=gpgpudeeplearn
#SBATCH --constraint=dlg5
#SBATCH --mem=120G
#SBATCH --mail-user=mingbinc@student.unimelb.edu.au
#SBATCH --mail-type=FAIL
#SBATCH --mail-type=BEGIN
#SBATCH --mail-type=END

# Add the export command here
export CUDA_LAUNCH_BLOCKING=1

source /data/projects/punim0478/bryan/anaconda3/bin/activate info_env
python3 calculate_entropy.py "$@"

##DO NOT ADD/EDIT BEYOND THIS LINE##
##Job monitor command to list the resource usage
my-job-stats -a -n -s

